### ISSUE TITLE
`yo.mark_read` does not mark items as read

### ISSUE THREAD

**Issue by relativityboy** [steemit/yo#15]
When attempting to mark two test notifications as read, do does not mark as such. Attempted the two following calls.

``` 
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "yo.mark_read",
    "params": {
      "test": true,
      "ids": [8307183, 937781]
    }
}  
```
_with strings because why not?_
``` 
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "yo.mark_read",
    "params": {
      "test": true,
      "ids": ["8307183", "937781"]
    }
}  
```

A quick look @ yo source suggests [the `ids` property specified in issues/10](https://github.com/steemit/yo/issues/10) might  be `notification_ids`, but have not been able to verify.

**Comment by GarethNelson** [comment]
Changed to ids

Please use integers and not strings.

**Comment by relativityboy** [comment]
Roger dodger captain commander. 

Thanks for the `ids`. :)

**Comment by relativityboy** [comment]
Still getting errors on mark_read -
Here's the payload
```
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "yo.mark_read",
    "params": {
      "test": true,
      "ids": [3231105, 3861489],
      "username": "test_user"
    }
}
```
Response
```
{
"jsonrpc": "2.0",
"error":{
"code": -32000,
"message": "Server error"
},
"id": 1
}
```
and server log from the request
```
INFO:jsonrpcserver.dispatcher.request:{'id': 1, 'jsonrpc': '2.0', 'method': 'yo.mark_read', 'params': {'test': True, 'ids': [3231105, 3861489], 'username': 'test_user', 'yo_app': <yo.app.YoApp object at 0x7f5420d9aba8>, 'yo_db': <yo.db.YoDatabase object at 0x7f5421b07898>, 'yo_config': <yo.config.YoConfigManager object at 0x7f5421b07550>, 'orig_req': {'id': 1, 'jsonrpc': '2.0', 'method': 'yo.mark_read', 'params': {'test': True, 'ids': [3231105, 3861489], 'username': 'test_user'}}, 'skip_auth': False}}
ERROR:jsonrpcserver.request:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jsonrpcserver/request.py", line 42, in handle_exceptions
    yield
  File "/usr/local/lib/python3.6/site-packages/jsonrpcserver/async_request.py", line 21, in call
    result = await callable_(*(self.args or []), **(self.kwargs or {}))
  File "/app/yo/api_server.py", line 74, in api_mark_read
    self.test_notifications.mark_read(notify_id)
AttributeError: 'YoMockData' object has no attribute 'mark_read'

INFO:jsonrpcserver.dispatcher.response:{"jsonrpc": "2.0", "error": {"code": -32000, "message": "Server error"}, "id": 1}
INFO:aiohttp.access:172.17.0.1 - - [12/Oct/2017:16:18:22 +0000] "POST / HTTP/1.1" 200 238 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
```

**Comment by relativityboy** [comment]
I don’t know if this is an issue in Yo master; the api was calling `mark_seen` & `mark_read` but the implementations in *YoMockData* were named `mark_notification_seen` and `mark_notification_read`. I've updated the branch with the correct calls for the mock object within the api.
