### ISSUE TITLE
current config breaks if sms transport credentials are missing

### ISSUE THREAD

**Issue by john-g-g** [steemit/yo#47]
```Enabled services: ['blockchain_follower', 'notification_sender', 'api_server']
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]: INFO:yo.db:Using sqlite engine for database storage
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]: INFO:yo.db:Creating/updating database schema...
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]: INFO:yo.db:Loading initdata from file data/init.json
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]: INFO:yo.db:Finished reading initdata file
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]: INFO:yo.db:DB Layer ready
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]: Traceback (most recent call last):
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:     "__main__", mod_spec)
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:     exec(code, run_globals)
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:   File "/app/yo/cli.py", line 35, in <module>
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:     main()
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:   File "/app/yo/cli.py", line 24, in main
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:     yo_app.add_service(sender)
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:   File "/app/yo/app.py", line 112, in add_service
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:     service.init_api(self)
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:   File "/app/yo/notification_sender.py", line 68, in init_api
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:     yo_app.config.config_data['twilio']['from_number'],
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:   File "/app/yo/transports/twilio.py", line 21, in __init__
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:     self.client = Client(account_sid, auth_token)
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:   File "/app/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/twilio/rest/__init__.py", line 47, in __init__
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]:     raise TwilioException("Credentials are required to create a TwilioClient")
15:29:18.000 steemit-dev-yo-001_i-017f1db715288d60e /var/log/messages Oct 26 19:29:18 ip-172-31-18-122 docker/c4a240d7f316[19302]: twilio.base.exceptions.TwilioException: Credentials are required to create a TwilioClient```

**Comment by GarethNelson** [comment]
Fix is to implement this:
https://github.com/steemit/yo/issues/51

Closing as duplicate
